version: '3.2'

services:
  cas:
    container_name: cas
    restart: always
    image: bulyginevgeny/cas_backend:${CAS_IMAGE_TAG}
    environment:
      BASE_ADDRESS: '${BASE_ADDRESS}'
    ports:
      - 80:8000
    networks:
      - my_network

  acs:
    container_name: acs
    restart: always
    image: bulyginevgeny/acs:${ACS_IMAGE_TAG}
    environment:
      BASE_ADDRESS: '${BASE_ADDRESS}'
      ACS_PORT: '${ACS_PORT}'
    ports:
      - 81:8001
    networks:
      - my_network

networks:
  my_network:
    driver: bridge
